# Generated by Django 4.2.20 on 2025-04-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_interview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="job_description_url",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
