# Generated by Django 4.2.20 on 2025-04-16 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_interview_job_description_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="interview",
            old_name="job_description_url",
            new_name="job_description",
        ),
    ]
