# Generated by Django 4.2.20 on 2025-04-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_completedinterview"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="certifications",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="domain_expertise",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="education",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="experience",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="projects",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="years_of_experience",
            field=models.FloatField(default=0),
        ),
    ]
