# Generated by Django 4.2.20 on 2025-04-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_resume_certifications_resume_domain_expertise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedinterview",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
