# Generated by Django 4.2.20 on 2025-10-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_completedinterview_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="interview_type",
        ),
        migrations.AddField(
            model_name="interview",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="interview",
            name="role",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
