# Generated by Django 4.2.20 on 2025-12-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_completedinterview_video_duration_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedinterview",
            name="engagement_score",
            field=models.FloatField(
                blank=True, help_text="Engagement score from vision model", null=True
            ),
        ),
        migrations.AddField(
            model_name="completedinterview",
            name="engaging_tone_score",
            field=models.FloatField(
                blank=True, help_text="Engaging Tone score from vision model", null=True
            ),
        ),
        migrations.AddField(
            model_name="completedinterview",
            name="excitement_score",
            field=models.FloatField(
                blank=True, help_text="Excitement score from vision model", null=True
            ),
        ),
        migrations.AddField(
            model_name="completedinterview",
            name="friendliness_score",
            field=models.FloatField(
                blank=True, help_text="Friendliness score from vision model", null=True
            ),
        ),
        migrations.AddField(
            model_name="completedinterview",
            name="smile_score",
            field=models.FloatField(
                blank=True, help_text="Smile score from vision model", null=True
            ),
        ),
    ]
