# Generated by Django 4.2.20 on 2025-12-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_completedinterview_engagement_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="email",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="location",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="years_of_experience",
        ),
        migrations.AddField(
            model_name="resume",
            name="academic_projects",
            field=models.JSONField(
                blank=True, help_text="Academic Projects", null=True
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="core_skills",
            field=models.JSONField(
                blank=True,
                help_text="List of Core skills (e.g., 'XGBoost', 'Forecasting', 'Optimization')",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="professional_projects",
            field=models.JSONField(
                blank=True, help_text="Professional Projects", null=True
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="project_domains",
            field=models.JSONField(
                blank=True,
                help_text="List of Project domains (e.g., 'Donor forecasting model', 'Route optimization')",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="total_experience",
            field=models.FloatField(default=0, help_text="Total Experience (in years)"),
        ),
        migrations.AddField(
            model_name="resume",
            name="work_context",
            field=models.JSONField(
                blank=True,
                help_text="List of Work context (e.g., 'BioLife Plasma Services', 'Healthcare analytics')",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="work_experience",
            field=models.JSONField(blank=True, help_text="Work Experience", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Candidate name from resume",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="skills",
            field=models.JSONField(blank=True, help_text="Skills", null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="summary",
            field=models.TextField(
                blank=True, help_text="Professional Summary", null=True
            ),
        ),
    ]
